💡 Add docstrings for podcasts
wdr-data/wdr-okr pull request #28
Opened 2020-11-12 00:14 UTC by tcmetzger

This pull request adds docstrings to several files related to podcast scrapers.

2020-11-12 00:21 UTC, tcmetzger commented
I'D appreciate some help with okr/scrapers/podcasts/spotify_api.py - I could use some info on the types returned by the various methods there .

2020-11-12 11:24 UTC, jh0ker requested changes
I left some comments.
 
Also, what happened in commmit c73063e3fcd92fef2e00828b6ce6270ea0345390 ? GitHub shows me the whole file as changed. Is that because of something like different line endings or is there really that much changed that it sees it as a completely new file?

2020-11-12 11:24 UTC, jh0ker commented on okr/scrapers/podcasts/__init__.py
> +        # Retrieve follower and listener data for podcast (ignores start_date)
Only follower data ignores `start_date`. Reason is that the API only supports querying the current follower number, no historic data is provided.

2020-11-13 03:18 UTC, tcmetzger commented on okr/scrapers/podcasts/feed.py
> +    return feedparser.parse(url)
Voll!

2020-11-13 09:47 UTC, jh0ker approved these changes

2020-11-13 09:47 UTC, merged